name: Get slack user ID
description: Get slack user ID from github username
inputs:
  user:
    description: Github username or email (use `github.triggering_actor` as default). multiple users can be specified with comma separated string.
    required: false
  mapping_file:
    required: false
    default: ''
    description: Custom github username to slack user id mapping json file path.
outputs:
  id:
    description: Slack user ID
    value: ${{ steps.slack-id.outputs.id }}
runs:
  using: composite
  steps:
    - name: Get slack user ID
      id: slack-id
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [ -z '${{ inputs.mapping_file }}' ]; then
          filepath='${{ github.action_path }}/map.json'
        else
          filepath='${{ inputs.mapping_file }}'
        fi

        keys=$(echo '${{ inputs.user || github.triggering_actor }}' | jq -Rr 'split(",") | @csv')

        # use `jq "{$keys}"` if you want key-value pair
        echo "id<<EOF" >> $GITHUB_OUTPUT
        jq -crMe ".[$keys]" "$filepath" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: User ID
      shell: bash
      run: echo '${{ steps.slack-id.outputs.id }}'
