name: Test Action
description: Test Action

inputs:
  markdown:
    description: Markdown
    required: true

runs:
  using: composition
  steps:
    - shell: bash
      run: echo ${{ inputs.markdown }}
