name: Send Slack Notification
description: Send notification to Slack channel.

inputs:
  slack-webhook-url:
    description: Slack Webhook URL
    required: true
  title:
    description: Title
    required: true
  is-success:
    type: boolean
    description: Success?
    required: true

runs:
  using: composite
  steps:
    - id: get-slack-user-id
      uses: ./.github/actions/get-slack-user-id
      with:
        user: ${{ github.event.pull_request.user.id }}
    - run: echo Slack Webhook URL ${{ inputs.slack-webhook-url }}
      shell: bash
    - id: generate-message
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const createTextElement = (text, bold = false) => ({ type: 'text', text, style: { bold } });
          const createUserElement = (user_id) => ({ type: 'user', user_id });
          return JSON.stringify({
            blocks: [
              {
                type: 'rich_text',
                elements: [
                  {
                    type: 'rich_text_section',
                    elements: [
                      createTextElement('${{ inputs.title }}', true),
                      createUserElement('${{ steps.get-slack-user-id.outputs.id }}'),
                    ],
                  },
                  {
                    type: 'rich_text_quote',
                    elements: [
                      createTextElement('Pull Request', true),
                      createUserElement('${{ github.event.pull_request.title }} <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>"'),
                    ],
                  },
                  {
                    type: 'rich_text_quote',
                    elements: [
                      createTextElement('Commit', true),
                      createUserElement('<${{ github.event.pull_request.html_url }}/commits/${{ github.event.pull_request.head.sha }}|${{ github.event.pull_request.head.sha }}>'),
                    ],
                  },
                  ${{ inputs.is-success }} ? {
                    type: 'rich_text_quote',
                    elements: [
                      createTextElement('Build ID', true),
                      createUserElement('${{ steps.get-slack-user-id.outputs.id }}'),
                    ],
                  } : {
                    type: 'rich_text_quote',
                    elements: [
                      createUserElement('⚠️ Please check the error on <${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|Workflow #${{ github.run_number }}>'),
                    ],
                  },
                ],
              },
            ],
          })
